apiVersion: v1alpha
kind: espresso

sauce:
  region: us-west-1
  concurrency: 1

espresso:
  app: storage:filename=smart-cinema-telemetry-suite-manual.apk
  testApp: storage:filename=smart-cinema-telemetry-suite-test-manual.apk

suites:
  - name: SmartCinema telemetry suite
    testOptions:
      class:
        - com.splunk.rum.flutter.root.exampleapp.root_example_app.MainActivityTest
    devices:
      - name: "Google Pixel.*"
