name: splunk_otel_flutter_session_replay
description: "Session replay module for Splunk OpenTelemetry Flutter. Captures and replays user sessions for debugging and analytics."
version: 1.0.0
repository: https://github.com/signalfx/splunk-otel-flutter/tree/main/packages/splunk_otel_flutter_session_replay/splunk_otel_flutter_session_replay
homepage: https://github.com/signalfx/splunk-otel-flutter

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.32.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  splunk_otel_flutter_platform_interface: ^1.0.0
  splunk_otel_flutter_session_replay_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.splunk.rum.flutter.sessionreplay.splunk_otel_flutter_session_replay
        pluginClass: SplunkOtelFlutterSessionReplayPlugin
      ios:
        pluginClass: SplunkOtelFlutterSessionReplayPlugin