extends:
  - "@commitlint/config-conventional"

rules:
  type-enum:
    - 2
    - always
    - [build, chore, ci, docs, feat, fix, perf, refactor, style, test, revert]
  subject-case:
    - 2
    - always
    - lower-case
  header-max-length:
    - 2
    - always
    - 72
  body-leading-blank:
    - 2
    - always
  footer-leading-blank:
    - 2
    - always