name: splunk_otel_workspace
publish_to: none
environment:
  sdk: '>=3.8.0 <4.0.0'

workspace:
  # Main Plugin
  - packages/splunk_otel_flutter/splunk_otel_flutter
  - packages/splunk_otel_flutter/splunk_otel_flutter_platform_interface
  - packages/splunk_otel_flutter/splunk_otel_flutter/example

  # Session Replay Plugin
  - packages/splunk_otel_flutter_session_replay/splunk_otel_flutter_session_replay
  - packages/splunk_otel_flutter_session_replay/splunk_otel_flutter_session_replay_platform_interface
  - packages/splunk_otel_flutter_session_replay/splunk_otel_flutter_session_replay/example

  # Example Application
  - splunk_otel_flutter_root_example_app

dev_dependencies:
  intl: ^0.20.2
  melos: ^7.1.1

melos:
  scripts:
    analyze:
      run: dart analyze --fatal-warnings .
      description: Run Dart analyzer across all packages.
    test:
      run: flutter test
      description: Run tests across all packages.
    format:
      run: dart format .
      description: Format code across all packages.
    clean:
      run: flutter clean
      description: Clean Flutter builds across all packages.
    
      # Script to generate Pigeon code for all interface packages.
      # Assumes Pigeon definitions (e.g., pigeons/*.dart) are located within the interface packages.
    generate_pigeon:
      run: |
        melos exec --scope="splunk_otel_flutter_platform_interface" -- flutter pub run pigeon --input pigeons/messages.dart
        melos exec --scope="splunk_otel_flutter_session_replay_platform_interface" -- flutter pub run pigeon --input pigeons/messages.dart
      description: Generates Pigeon code for all packages.
    
    run_example:
      run: flutter run
      scope: example
      description: Run the example application.
