// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, unnecessary_import, no_leading_underscores_for_local_identifiers
// ignore_for_file: avoid_relative_lib_imports
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;
import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:splunk_otel_flutter_platform_interface/src/pigeon/messages.pigeon.dart';


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is GeneratedUserTrackingMode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is GeneratedSlowRenderingModuleConfiguration) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is GeneratedNavigationModuleConfiguration) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is GeneratedAgentConfiguration) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is GeneratedEndpointConfiguration) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is GeneratedUserConfiguration) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is GeneratedSessionConfiguration) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : GeneratedUserTrackingMode.values[value];
      case 130: 
        return GeneratedSlowRenderingModuleConfiguration.decode(readValue(buffer)!);
      case 131: 
        return GeneratedNavigationModuleConfiguration.decode(readValue(buffer)!);
      case 132: 
        return GeneratedAgentConfiguration.decode(readValue(buffer)!);
      case 133: 
        return GeneratedEndpointConfiguration.decode(readValue(buffer)!);
      case 134: 
        return GeneratedUserConfiguration.decode(readValue(buffer)!);
      case 135: 
        return GeneratedSessionConfiguration.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class TestSplunkOtelFlutterHostApi {
  static TestDefaultBinaryMessengerBinding? get _testBinaryMessengerBinding => TestDefaultBinaryMessengerBinding.instance;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  Future<void> install({required GeneratedAgentConfiguration agentConfiguration, required GeneratedNavigationModuleConfiguration navigationModuleConfiguration, required GeneratedSlowRenderingModuleConfiguration slowRenderingModuleConfiguration, });

  Future<void> sessionReplayStart();

  Future<String> getSessionId();

  static void setUp(TestSplunkOtelFlutterHostApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.install$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.install was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final GeneratedAgentConfiguration? arg_agentConfiguration = (args[0] as GeneratedAgentConfiguration?);
          assert(arg_agentConfiguration != null,
              'Argument for dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.install was null, expected non-null GeneratedAgentConfiguration.');
          final GeneratedNavigationModuleConfiguration? arg_navigationModuleConfiguration = (args[1] as GeneratedNavigationModuleConfiguration?);
          assert(arg_navigationModuleConfiguration != null,
              'Argument for dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.install was null, expected non-null GeneratedNavigationModuleConfiguration.');
          final GeneratedSlowRenderingModuleConfiguration? arg_slowRenderingModuleConfiguration = (args[2] as GeneratedSlowRenderingModuleConfiguration?);
          assert(arg_slowRenderingModuleConfiguration != null,
              'Argument for dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.install was null, expected non-null GeneratedSlowRenderingModuleConfiguration.');
          try {
            await api.install(agentConfiguration: arg_agentConfiguration!, navigationModuleConfiguration: arg_navigationModuleConfiguration!, slowRenderingModuleConfiguration: arg_slowRenderingModuleConfiguration!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.sessionReplayStart$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (Object? message) async {
          try {
            await api.sessionReplayStart();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.getSessionId$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, null);
      } else {
        _testBinaryMessengerBinding!.defaultBinaryMessenger.setMockDecodedMessageHandler<Object?>(pigeonVar_channel, (Object? message) async {
          try {
            final String output = await api.getSessionId();
            return <Object?>[output];
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
