// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


enum GeneratedUserTrackingMode {
  noTracking,
  anonymousTracking,
}

class GeneratedSlowRenderingModuleConfiguration {
  GeneratedSlowRenderingModuleConfiguration({
    required this.isEnabled,
    required this.intervalMillis,
  });

  bool isEnabled;

  int intervalMillis;

  List<Object?> _toList() {
    return <Object?>[
      isEnabled,
      intervalMillis,
    ];
  }

  Object encode() {
    return _toList();  }

  static GeneratedSlowRenderingModuleConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedSlowRenderingModuleConfiguration(
      isEnabled: result[0]! as bool,
      intervalMillis: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedSlowRenderingModuleConfiguration || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class GeneratedNavigationModuleConfiguration {
  GeneratedNavigationModuleConfiguration({
    required this.isEnabled,
    required this.isAutomatedTrackingEnabled,
  });

  bool isEnabled;

  bool isAutomatedTrackingEnabled;

  List<Object?> _toList() {
    return <Object?>[
      isEnabled,
      isAutomatedTrackingEnabled,
    ];
  }

  Object encode() {
    return _toList();  }

  static GeneratedNavigationModuleConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedNavigationModuleConfiguration(
      isEnabled: result[0]! as bool,
      isAutomatedTrackingEnabled: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedNavigationModuleConfiguration || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class GeneratedAgentConfiguration {
  GeneratedAgentConfiguration({
    required this.endpoint,
    required this.appName,
    required this.deploymentEnvironment,
    this.appVersion,
    required this.enableDebugLogging,
    required this.globalAttributes,
    required this.user,
    required this.session,
    this.instrumentedProcessName,
    required this.deferredUntilForeground,
  });

  GeneratedEndpointConfiguration endpoint;

  String appName;

  String deploymentEnvironment;

  String? appVersion;

  bool enableDebugLogging;

  Map<String, Object?> globalAttributes;

  GeneratedUserConfiguration user;

  GeneratedSessionConfiguration session;

  String? instrumentedProcessName;

  bool deferredUntilForeground;

  List<Object?> _toList() {
    return <Object?>[
      endpoint,
      appName,
      deploymentEnvironment,
      appVersion,
      enableDebugLogging,
      globalAttributes,
      user,
      session,
      instrumentedProcessName,
      deferredUntilForeground,
    ];
  }

  Object encode() {
    return _toList();  }

  static GeneratedAgentConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedAgentConfiguration(
      endpoint: result[0]! as GeneratedEndpointConfiguration,
      appName: result[1]! as String,
      deploymentEnvironment: result[2]! as String,
      appVersion: result[3] as String?,
      enableDebugLogging: result[4]! as bool,
      globalAttributes: (result[5] as Map<Object?, Object?>?)!.cast<String, Object?>(),
      user: result[6]! as GeneratedUserConfiguration,
      session: result[7]! as GeneratedSessionConfiguration,
      instrumentedProcessName: result[8] as String?,
      deferredUntilForeground: result[9]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedAgentConfiguration || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class GeneratedEndpointConfiguration {
  GeneratedEndpointConfiguration({
    required this.realm,
    required this.rumAccessToken,
  });

  String realm;

  String rumAccessToken;

  List<Object?> _toList() {
    return <Object?>[
      realm,
      rumAccessToken,
    ];
  }

  Object encode() {
    return _toList();  }

  static GeneratedEndpointConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedEndpointConfiguration(
      realm: result[0]! as String,
      rumAccessToken: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedEndpointConfiguration || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class GeneratedUserConfiguration {
  GeneratedUserConfiguration({
    required this.trackingMode,
  });

  GeneratedUserTrackingMode trackingMode;

  List<Object?> _toList() {
    return <Object?>[
      trackingMode,
    ];
  }

  Object encode() {
    return _toList();  }

  static GeneratedUserConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedUserConfiguration(
      trackingMode: result[0]! as GeneratedUserTrackingMode,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedUserConfiguration || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class GeneratedSessionConfiguration {
  GeneratedSessionConfiguration({
    required this.samplingRate,
  });

  double samplingRate;

  List<Object?> _toList() {
    return <Object?>[
      samplingRate,
    ];
  }

  Object encode() {
    return _toList();  }

  static GeneratedSessionConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedSessionConfiguration(
      samplingRate: result[0]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedSessionConfiguration || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is GeneratedUserTrackingMode) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is GeneratedSlowRenderingModuleConfiguration) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is GeneratedNavigationModuleConfiguration) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is GeneratedAgentConfiguration) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is GeneratedEndpointConfiguration) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is GeneratedUserConfiguration) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is GeneratedSessionConfiguration) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : GeneratedUserTrackingMode.values[value];
      case 130: 
        return GeneratedSlowRenderingModuleConfiguration.decode(readValue(buffer)!);
      case 131: 
        return GeneratedNavigationModuleConfiguration.decode(readValue(buffer)!);
      case 132: 
        return GeneratedAgentConfiguration.decode(readValue(buffer)!);
      case 133: 
        return GeneratedEndpointConfiguration.decode(readValue(buffer)!);
      case 134: 
        return GeneratedUserConfiguration.decode(readValue(buffer)!);
      case 135: 
        return GeneratedSessionConfiguration.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class SplunkOtelFlutterHostApi {
  /// Constructor for [SplunkOtelFlutterHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SplunkOtelFlutterHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> install({required GeneratedAgentConfiguration agentConfiguration, required GeneratedNavigationModuleConfiguration navigationModuleConfiguration, required GeneratedSlowRenderingModuleConfiguration slowRenderingModuleConfiguration, }) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.install$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[agentConfiguration, navigationModuleConfiguration, slowRenderingModuleConfiguration]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> sessionReplayStart() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.sessionReplayStart$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> getSessionId() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.getSessionId$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }
}
