// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum GeneratedRegexOption {
  caseInsensitive,
  allowCommentsAndWhitespace,
  ignoreMetacharacters,
  dotMatchesLineSeparators,
  anchorsMatchLines,
  useUnixLineSeparators,
  useUnicodeWordBoundaries,
}

enum GeneratedUserTrackingMode { noTracking, anonymousTracking }

enum GeneratedSessionReplayStatus {
  isRecording,
  notStarted,
  stopped,
  belowMinSdkVersion,
  storageLimitReached,
  internalError,
  disabledBySampling,
}

enum GeneratedRecordingMaskType { erasing, covering }

enum GeneratedStatus {
  running,
  notInstalled,
  subprocess,
  sampledOut,
  unsupportedPlatform,
  unsupportedOsVersion,
}

class GeneratedSlowRenderingModuleConfiguration {
  GeneratedSlowRenderingModuleConfiguration({
    required this.isEnabled,
    required this.intervalMillis,
  });

  bool isEnabled;

  int intervalMillis;

  List<Object?> _toList() {
    return <Object?>[isEnabled, intervalMillis];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedSlowRenderingModuleConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedSlowRenderingModuleConfiguration(
      isEnabled: result[0]! as bool,
      intervalMillis: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedSlowRenderingModuleConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isEnabled, other.isEnabled) &&
        _deepEquals(intervalMillis, other.intervalMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedNavigationModuleConfiguration {
  GeneratedNavigationModuleConfiguration({
    required this.isEnabled,
    required this.isAutomatedTrackingEnabled,
  });

  bool isEnabled;

  bool isAutomatedTrackingEnabled;

  List<Object?> _toList() {
    return <Object?>[isEnabled, isAutomatedTrackingEnabled];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedNavigationModuleConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedNavigationModuleConfiguration(
      isEnabled: result[0]! as bool,
      isAutomatedTrackingEnabled: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedNavigationModuleConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isEnabled, other.isEnabled) &&
        _deepEquals(
          isAutomatedTrackingEnabled,
          other.isAutomatedTrackingEnabled,
        );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedCrashReportsModuleConfiguration {
  GeneratedCrashReportsModuleConfiguration({required this.isEnabled});

  bool isEnabled;

  List<Object?> _toList() {
    return <Object?>[isEnabled];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedCrashReportsModuleConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedCrashReportsModuleConfiguration(
      isEnabled: result[0]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedCrashReportsModuleConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isEnabled, other.isEnabled);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedInteractionsModuleConfiguration {
  GeneratedInteractionsModuleConfiguration({required this.isEnabled});

  bool isEnabled;

  List<Object?> _toList() {
    return <Object?>[isEnabled];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedInteractionsModuleConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedInteractionsModuleConfiguration(
      isEnabled: result[0]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedInteractionsModuleConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isEnabled, other.isEnabled);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedNetworkMonitorModuleConfiguration {
  GeneratedNetworkMonitorModuleConfiguration({required this.isEnabled});

  bool isEnabled;

  List<Object?> _toList() {
    return <Object?>[isEnabled];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedNetworkMonitorModuleConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedNetworkMonitorModuleConfiguration(
      isEnabled: result[0]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedNetworkMonitorModuleConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isEnabled, other.isEnabled);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedApplicationLifecycleModuleConfiguration {
  GeneratedApplicationLifecycleModuleConfiguration({required this.isEnabled});

  bool isEnabled;

  List<Object?> _toList() {
    return <Object?>[isEnabled];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedApplicationLifecycleModuleConfiguration decode(
    Object result,
  ) {
    result as List<Object?>;
    return GeneratedApplicationLifecycleModuleConfiguration(
      isEnabled: result[0]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedApplicationLifecycleModuleConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isEnabled, other.isEnabled);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedAnrModuleConfiguration {
  GeneratedAnrModuleConfiguration({required this.isEnabled});

  bool isEnabled;

  List<Object?> _toList() {
    return <Object?>[isEnabled];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedAnrModuleConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedAnrModuleConfiguration(isEnabled: result[0]! as bool);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedAnrModuleConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isEnabled, other.isEnabled);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedHttpUrlModuleConfiguration {
  GeneratedHttpUrlModuleConfiguration({
    required this.isEnabled,
    required this.capturedRequestHeaders,
    required this.capturedResponseHeaders,
  });

  bool isEnabled;

  List<String> capturedRequestHeaders;

  List<String> capturedResponseHeaders;

  List<Object?> _toList() {
    return <Object?>[
      isEnabled,
      capturedRequestHeaders,
      capturedResponseHeaders,
    ];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedHttpUrlModuleConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedHttpUrlModuleConfiguration(
      isEnabled: result[0]! as bool,
      capturedRequestHeaders: (result[1]! as List<Object?>).cast<String>(),
      capturedResponseHeaders: (result[2]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedHttpUrlModuleConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isEnabled, other.isEnabled) &&
        _deepEquals(capturedRequestHeaders, other.capturedRequestHeaders) &&
        _deepEquals(capturedResponseHeaders, other.capturedResponseHeaders);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedOkHttp3AutoModuleConfiguration {
  GeneratedOkHttp3AutoModuleConfiguration({
    required this.isEnabled,
    required this.capturedRequestHeaders,
    required this.capturedResponseHeaders,
  });

  bool isEnabled;

  List<String> capturedRequestHeaders;

  List<String> capturedResponseHeaders;

  List<Object?> _toList() {
    return <Object?>[
      isEnabled,
      capturedRequestHeaders,
      capturedResponseHeaders,
    ];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedOkHttp3AutoModuleConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedOkHttp3AutoModuleConfiguration(
      isEnabled: result[0]! as bool,
      capturedRequestHeaders: (result[1]! as List<Object?>).cast<String>(),
      capturedResponseHeaders: (result[2]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedOkHttp3AutoModuleConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isEnabled, other.isEnabled) &&
        _deepEquals(capturedRequestHeaders, other.capturedRequestHeaders) &&
        _deepEquals(capturedResponseHeaders, other.capturedResponseHeaders);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedNetworkInstrumentationModuleConfiguration {
  GeneratedNetworkInstrumentationModuleConfiguration({
    required this.isEnabled,
    required this.ignoreURLs,
    required this.capturedRequestHeaders,
    required this.capturedResponseHeaders,
  });

  bool isEnabled;

  List<GeneratedRegularExpression> ignoreURLs;

  List<String> capturedRequestHeaders;

  List<String> capturedResponseHeaders;

  List<Object?> _toList() {
    return <Object?>[
      isEnabled,
      ignoreURLs,
      capturedRequestHeaders,
      capturedResponseHeaders,
    ];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedNetworkInstrumentationModuleConfiguration decode(
    Object result,
  ) {
    result as List<Object?>;
    return GeneratedNetworkInstrumentationModuleConfiguration(
      isEnabled: result[0]! as bool,
      ignoreURLs: (result[1]! as List<Object?>)
          .cast<GeneratedRegularExpression>(),
      capturedRequestHeaders: (result[2]! as List<Object?>).cast<String>(),
      capturedResponseHeaders: (result[3]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedNetworkInstrumentationModuleConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isEnabled, other.isEnabled) &&
        _deepEquals(ignoreURLs, other.ignoreURLs) &&
        _deepEquals(capturedRequestHeaders, other.capturedRequestHeaders) &&
        _deepEquals(capturedResponseHeaders, other.capturedResponseHeaders);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedRegularExpression {
  GeneratedRegularExpression({required this.pattern, this.options});

  String pattern;

  List<GeneratedRegexOption?>? options;

  List<Object?> _toList() {
    return <Object?>[pattern, options];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedRegularExpression decode(Object result) {
    result as List<Object?>;
    return GeneratedRegularExpression(
      pattern: result[0]! as String,
      options: (result[1] as List<Object?>?)?.cast<GeneratedRegexOption?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedRegularExpression ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pattern, other.pattern) &&
        _deepEquals(options, other.options);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedSessionReplayModuleConfiguration {
  GeneratedSessionReplayModuleConfiguration({
    required this.isEnabled,
    required this.samplingRate,
  });

  bool isEnabled;

  double samplingRate;

  List<Object?> _toList() {
    return <Object?>[isEnabled, samplingRate];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedSessionReplayModuleConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedSessionReplayModuleConfiguration(
      isEnabled: result[0]! as bool,
      samplingRate: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedSessionReplayModuleConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isEnabled, other.isEnabled) &&
        _deepEquals(samplingRate, other.samplingRate);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedAgentConfiguration {
  GeneratedAgentConfiguration({
    required this.appName,
    required this.deploymentEnvironment,
    this.endpoint,
    this.appVersion,
    this.enableDebugLogging,
    this.globalAttributes,
    this.user,
    this.session,
    this.instrumentedProcessName,
    this.deferredUntilForeground,
  });

  String appName;

  String deploymentEnvironment;

  GeneratedEndpointConfiguration? endpoint;

  String? appVersion;

  bool? enableDebugLogging;

  GeneratedMutableAttributes? globalAttributes;

  GeneratedUserConfiguration? user;

  GeneratedSessionConfiguration? session;

  String? instrumentedProcessName;

  bool? deferredUntilForeground;

  List<Object?> _toList() {
    return <Object?>[
      appName,
      deploymentEnvironment,
      endpoint,
      appVersion,
      enableDebugLogging,
      globalAttributes,
      user,
      session,
      instrumentedProcessName,
      deferredUntilForeground,
    ];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedAgentConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedAgentConfiguration(
      appName: result[0]! as String,
      deploymentEnvironment: result[1]! as String,
      endpoint: result[2] as GeneratedEndpointConfiguration?,
      appVersion: result[3] as String?,
      enableDebugLogging: result[4] as bool?,
      globalAttributes: result[5] as GeneratedMutableAttributes?,
      user: result[6] as GeneratedUserConfiguration?,
      session: result[7] as GeneratedSessionConfiguration?,
      instrumentedProcessName: result[8] as String?,
      deferredUntilForeground: result[9] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedAgentConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(appName, other.appName) &&
        _deepEquals(deploymentEnvironment, other.deploymentEnvironment) &&
        _deepEquals(endpoint, other.endpoint) &&
        _deepEquals(appVersion, other.appVersion) &&
        _deepEquals(enableDebugLogging, other.enableDebugLogging) &&
        _deepEquals(globalAttributes, other.globalAttributes) &&
        _deepEquals(user, other.user) &&
        _deepEquals(session, other.session) &&
        _deepEquals(instrumentedProcessName, other.instrumentedProcessName) &&
        _deepEquals(deferredUntilForeground, other.deferredUntilForeground);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedEndpointConfiguration {
  GeneratedEndpointConfiguration({
    this.traceEndpoint,
    this.sessionReplayEndpoint,
    this.realm,
    this.rumAccessToken,
  });

  String? traceEndpoint;

  String? sessionReplayEndpoint;

  String? realm;

  String? rumAccessToken;

  List<Object?> _toList() {
    return <Object?>[
      traceEndpoint,
      sessionReplayEndpoint,
      realm,
      rumAccessToken,
    ];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedEndpointConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedEndpointConfiguration(
      traceEndpoint: result[0] as String?,
      sessionReplayEndpoint: result[1] as String?,
      realm: result[2] as String?,
      rumAccessToken: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedEndpointConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(traceEndpoint, other.traceEndpoint) &&
        _deepEquals(sessionReplayEndpoint, other.sessionReplayEndpoint) &&
        _deepEquals(realm, other.realm) &&
        _deepEquals(rumAccessToken, other.rumAccessToken);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedUserConfiguration {
  GeneratedUserConfiguration({required this.trackingMode});

  GeneratedUserTrackingMode trackingMode;

  List<Object?> _toList() {
    return <Object?>[trackingMode];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedUserConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedUserConfiguration(
      trackingMode: result[0]! as GeneratedUserTrackingMode,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedUserConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(trackingMode, other.trackingMode);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedSessionConfiguration {
  GeneratedSessionConfiguration({required this.samplingRate});

  double samplingRate;

  List<Object?> _toList() {
    return <Object?>[samplingRate];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedSessionConfiguration decode(Object result) {
    result as List<Object?>;
    return GeneratedSessionConfiguration(samplingRate: result[0]! as double);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedSessionConfiguration ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(samplingRate, other.samplingRate);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedRecordingMaskList {
  GeneratedRecordingMaskList({this.recordingMaskList});

  List<GeneratedRecordingMaskElement>? recordingMaskList;

  List<Object?> _toList() {
    return <Object?>[recordingMaskList];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedRecordingMaskList decode(Object result) {
    result as List<Object?>;
    return GeneratedRecordingMaskList(
      recordingMaskList: (result[0] as List<Object?>?)
          ?.cast<GeneratedRecordingMaskElement>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedRecordingMaskList ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(recordingMaskList, other.recordingMaskList);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedRecordingMaskElement {
  GeneratedRecordingMaskElement({required this.rect, required this.type});

  GeneratedRect rect;

  GeneratedRecordingMaskType type;

  List<Object?> _toList() {
    return <Object?>[rect, type];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedRecordingMaskElement decode(Object result) {
    result as List<Object?>;
    return GeneratedRecordingMaskElement(
      rect: result[0]! as GeneratedRect,
      type: result[1]! as GeneratedRecordingMaskType,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedRecordingMaskElement ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(rect, other.rect) && _deepEquals(type, other.type);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedRect {
  GeneratedRect({
    required this.left,
    required this.top,
    required this.width,
    required this.height,
  });

  double left;

  double top;

  double width;

  double height;

  List<Object?> _toList() {
    return <Object?>[left, top, width, height];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedRect decode(Object result) {
    result as List<Object?>;
    return GeneratedRect(
      left: result[0]! as double,
      top: result[1]! as double,
      width: result[2]! as double,
      height: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedRect || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(left, other.left) &&
        _deepEquals(top, other.top) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedError {
  GeneratedError({
    required this.type,
    required this.message,
    this.stacktrace,
    this.attributes,
    required this.source,
    required this.handled,
  });

  String type;

  String message;

  String? stacktrace;

  GeneratedMutableAttributes? attributes;

  String source;

  bool handled;

  List<Object?> _toList() {
    return <Object?>[type, message, stacktrace, attributes, source, handled];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedError decode(Object result) {
    result as List<Object?>;
    return GeneratedError(
      type: result[0]! as String,
      message: result[1]! as String,
      stacktrace: result[2] as String?,
      attributes: result[3] as GeneratedMutableAttributes?,
      source: result[4]! as String,
      handled: result[5]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedError || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) &&
        _deepEquals(message, other.message) &&
        _deepEquals(stacktrace, other.stacktrace) &&
        _deepEquals(attributes, other.attributes) &&
        _deepEquals(source, other.source) &&
        _deepEquals(handled, other.handled);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedMutableAttributes {
  GeneratedMutableAttributes({required this.attributes});

  Map<String, Object?> attributes;

  List<Object?> _toList() {
    return <Object?>[attributes];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedMutableAttributes decode(Object result) {
    result as List<Object?>;
    return GeneratedMutableAttributes(
      attributes: (result[0]! as Map<Object?, Object?>).cast<String, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedMutableAttributes ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(attributes, other.attributes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedMutableAttributeInt {
  GeneratedMutableAttributeInt({required this.value});

  int value;

  List<Object?> _toList() {
    return <Object?>[value];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedMutableAttributeInt decode(Object result) {
    result as List<Object?>;
    return GeneratedMutableAttributeInt(value: result[0]! as int);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedMutableAttributeInt ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedMutableAttributeDouble {
  GeneratedMutableAttributeDouble({required this.value});

  double value;

  List<Object?> _toList() {
    return <Object?>[value];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedMutableAttributeDouble decode(Object result) {
    result as List<Object?>;
    return GeneratedMutableAttributeDouble(value: result[0]! as double);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedMutableAttributeDouble ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedMutableAttributeString {
  GeneratedMutableAttributeString({required this.value});

  String value;

  List<Object?> _toList() {
    return <Object?>[value];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedMutableAttributeString decode(Object result) {
    result as List<Object?>;
    return GeneratedMutableAttributeString(value: result[0]! as String);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedMutableAttributeString ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedMutableAttributeBool {
  GeneratedMutableAttributeBool({required this.value});

  bool value;

  List<Object?> _toList() {
    return <Object?>[value];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedMutableAttributeBool decode(Object result) {
    result as List<Object?>;
    return GeneratedMutableAttributeBool(value: result[0]! as bool);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedMutableAttributeBool ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedMutableAttributeListInt {
  GeneratedMutableAttributeListInt({required this.value});

  List<int> value;

  List<Object?> _toList() {
    return <Object?>[value];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedMutableAttributeListInt decode(Object result) {
    result as List<Object?>;
    return GeneratedMutableAttributeListInt(
      value: (result[0]! as List<Object?>).cast<int>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedMutableAttributeListInt ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedMutableAttributeListDouble {
  GeneratedMutableAttributeListDouble({required this.value});

  List<double> value;

  List<Object?> _toList() {
    return <Object?>[value];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedMutableAttributeListDouble decode(Object result) {
    result as List<Object?>;
    return GeneratedMutableAttributeListDouble(
      value: (result[0]! as List<Object?>).cast<double>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedMutableAttributeListDouble ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedMutableAttributeListString {
  GeneratedMutableAttributeListString({required this.value});

  List<String> value;

  List<Object?> _toList() {
    return <Object?>[value];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedMutableAttributeListString decode(Object result) {
    result as List<Object?>;
    return GeneratedMutableAttributeListString(
      value: (result[0]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedMutableAttributeListString ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class GeneratedMutableAttributeListBool {
  GeneratedMutableAttributeListBool({required this.value});

  List<bool> value;

  List<Object?> _toList() {
    return <Object?>[value];
  }

  Object encode() {
    return _toList();
  }

  static GeneratedMutableAttributeListBool decode(Object result) {
    result as List<Object?>;
    return GeneratedMutableAttributeListBool(
      value: (result[0]! as List<Object?>).cast<bool>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GeneratedMutableAttributeListBool ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(value, other.value);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is GeneratedRegexOption) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is GeneratedUserTrackingMode) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is GeneratedSessionReplayStatus) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is GeneratedRecordingMaskType) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is GeneratedStatus) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is GeneratedSlowRenderingModuleConfiguration) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedNavigationModuleConfiguration) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedCrashReportsModuleConfiguration) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedInteractionsModuleConfiguration) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedNetworkMonitorModuleConfiguration) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedApplicationLifecycleModuleConfiguration) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedAnrModuleConfiguration) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedHttpUrlModuleConfiguration) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedOkHttp3AutoModuleConfiguration) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedNetworkInstrumentationModuleConfiguration) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedRegularExpression) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedSessionReplayModuleConfiguration) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedAgentConfiguration) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedEndpointConfiguration) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedUserConfiguration) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedSessionConfiguration) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedRecordingMaskList) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedRecordingMaskElement) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedRect) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedError) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedMutableAttributes) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedMutableAttributeInt) {
      buffer.putUint8(155);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedMutableAttributeDouble) {
      buffer.putUint8(156);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedMutableAttributeString) {
      buffer.putUint8(157);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedMutableAttributeBool) {
      buffer.putUint8(158);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedMutableAttributeListInt) {
      buffer.putUint8(159);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedMutableAttributeListDouble) {
      buffer.putUint8(160);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedMutableAttributeListString) {
      buffer.putUint8(161);
      writeValue(buffer, value.encode());
    } else if (value is GeneratedMutableAttributeListBool) {
      buffer.putUint8(162);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : GeneratedRegexOption.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : GeneratedUserTrackingMode.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null
            ? null
            : GeneratedSessionReplayStatus.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : GeneratedRecordingMaskType.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : GeneratedStatus.values[value];
      case 134:
        return GeneratedSlowRenderingModuleConfiguration.decode(
          readValue(buffer)!,
        );
      case 135:
        return GeneratedNavigationModuleConfiguration.decode(
          readValue(buffer)!,
        );
      case 136:
        return GeneratedCrashReportsModuleConfiguration.decode(
          readValue(buffer)!,
        );
      case 137:
        return GeneratedInteractionsModuleConfiguration.decode(
          readValue(buffer)!,
        );
      case 138:
        return GeneratedNetworkMonitorModuleConfiguration.decode(
          readValue(buffer)!,
        );
      case 139:
        return GeneratedApplicationLifecycleModuleConfiguration.decode(
          readValue(buffer)!,
        );
      case 140:
        return GeneratedAnrModuleConfiguration.decode(readValue(buffer)!);
      case 141:
        return GeneratedHttpUrlModuleConfiguration.decode(readValue(buffer)!);
      case 142:
        return GeneratedOkHttp3AutoModuleConfiguration.decode(
          readValue(buffer)!,
        );
      case 143:
        return GeneratedNetworkInstrumentationModuleConfiguration.decode(
          readValue(buffer)!,
        );
      case 144:
        return GeneratedRegularExpression.decode(readValue(buffer)!);
      case 145:
        return GeneratedSessionReplayModuleConfiguration.decode(
          readValue(buffer)!,
        );
      case 146:
        return GeneratedAgentConfiguration.decode(readValue(buffer)!);
      case 147:
        return GeneratedEndpointConfiguration.decode(readValue(buffer)!);
      case 148:
        return GeneratedUserConfiguration.decode(readValue(buffer)!);
      case 149:
        return GeneratedSessionConfiguration.decode(readValue(buffer)!);
      case 150:
        return GeneratedRecordingMaskList.decode(readValue(buffer)!);
      case 151:
        return GeneratedRecordingMaskElement.decode(readValue(buffer)!);
      case 152:
        return GeneratedRect.decode(readValue(buffer)!);
      case 153:
        return GeneratedError.decode(readValue(buffer)!);
      case 154:
        return GeneratedMutableAttributes.decode(readValue(buffer)!);
      case 155:
        return GeneratedMutableAttributeInt.decode(readValue(buffer)!);
      case 156:
        return GeneratedMutableAttributeDouble.decode(readValue(buffer)!);
      case 157:
        return GeneratedMutableAttributeString.decode(readValue(buffer)!);
      case 158:
        return GeneratedMutableAttributeBool.decode(readValue(buffer)!);
      case 159:
        return GeneratedMutableAttributeListInt.decode(readValue(buffer)!);
      case 160:
        return GeneratedMutableAttributeListDouble.decode(readValue(buffer)!);
      case 161:
        return GeneratedMutableAttributeListString.decode(readValue(buffer)!);
      case 162:
        return GeneratedMutableAttributeListBool.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class SplunkOtelFlutterHostApi {
  /// Constructor for [SplunkOtelFlutterHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SplunkOtelFlutterHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> install({
    required GeneratedAgentConfiguration agentConfiguration,
    required GeneratedNavigationModuleConfiguration?
    navigationModuleConfiguration,
    required GeneratedSlowRenderingModuleConfiguration?
    slowRenderingModuleConfiguration,
    required GeneratedCrashReportsModuleConfiguration?
    crashReportsModuleConfiguration,
    required GeneratedInteractionsModuleConfiguration?
    interactionsModuleConfiguration,
    required GeneratedNetworkMonitorModuleConfiguration?
    networkMonitorModuleConfiguration,
    required GeneratedApplicationLifecycleModuleConfiguration?
    applicationLifecycleModuleConfiguration,
    required GeneratedAnrModuleConfiguration? anrModuleConfiguration,
    required GeneratedHttpUrlModuleConfiguration? httpUrlModuleConfiguration,
    required GeneratedOkHttp3AutoModuleConfiguration?
    okHttp3AutoModuleConfiguration,
    required GeneratedNetworkInstrumentationModuleConfiguration?
    networkInstrumentationModuleConfiguration,
    required GeneratedSessionReplayModuleConfiguration?
    sessionReplayModuleConfiguration,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.install$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel
        .send(<Object?>[
          agentConfiguration,
          navigationModuleConfiguration,
          slowRenderingModuleConfiguration,
          crashReportsModuleConfiguration,
          interactionsModuleConfiguration,
          networkMonitorModuleConfiguration,
          applicationLifecycleModuleConfiguration,
          anrModuleConfiguration,
          httpUrlModuleConfiguration,
          okHttp3AutoModuleConfiguration,
          networkInstrumentationModuleConfiguration,
          sessionReplayModuleConfiguration,
        ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<String> stateGetAppName() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.stateGetAppName$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<String> stateGetAppVersion() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.stateGetAppVersion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<GeneratedStatus> stateGetStatus() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.stateGetStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as GeneratedStatus;
  }

  Future<GeneratedEndpointConfiguration?>
  stateGetEndpointConfiguration() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.stateGetEndpointConfiguration$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as GeneratedEndpointConfiguration?;
  }

  Future<String> stateGetDeploymentEnvironment() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.stateGetDeploymentEnvironment$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<bool> stateGetIsDebugLoggingEnabled() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.stateGetIsDebugLoggingEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<String?> stateGetInstrumentedProcessName() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.stateGetInstrumentedProcessName$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<bool> stateGetDeferredUntilForeground() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.stateGetDeferredUntilForeground$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<GeneratedEndpointConfiguration?>
  preferencesGetEndpointConfiguration() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.preferencesGetEndpointConfiguration$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as GeneratedEndpointConfiguration?;
  }

  Future<void> preferencesSetEndpointConfiguration({
    required GeneratedEndpointConfiguration endpointConfiguration,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.preferencesSetEndpointConfiguration$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[endpointConfiguration],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<String> sessionStateGetId() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.sessionStateGetId$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<double> sessionStateGetSamplingRate() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.sessionStateGetSamplingRate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as double;
  }

  Future<GeneratedUserTrackingMode> userStateGetUserTrackingMode() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.userStateGetUserTrackingMode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as GeneratedUserTrackingMode;
  }

  Future<GeneratedUserTrackingMode?>
  userPreferencesGetUserTrackingMode() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.userPreferencesGetUserTrackingMode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as GeneratedUserTrackingMode?;
  }

  Future<void> userPreferencesSetUserTrackingMode({
    required GeneratedUserTrackingMode trackingMode,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.userPreferencesSetUserTrackingMode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[trackingMode],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<Object?> globalAttributesGet({required String key}) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.globalAttributesGet$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue;
  }

  Future<GeneratedMutableAttributes?> globalAttributesGetAll() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.globalAttributesGetAll$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as GeneratedMutableAttributes?;
  }

  Future<void> globalAttributesRemove({required String key}) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.globalAttributesRemove$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> globalAttributesRemoveAll() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.globalAttributesRemoveAll$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<bool> globalAttributesContains({required String key}) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.globalAttributesContains$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> globalAttributesSetString({
    required String key,
    required String value,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.globalAttributesSetString$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key, value],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> globalAttributesSetInt({
    required String key,
    required int value,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.globalAttributesSetInt$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key, value],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> globalAttributesSetDouble({
    required String key,
    required double value,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.globalAttributesSetDouble$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key, value],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> globalAttributesSetBool({
    required String key,
    required bool value,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.globalAttributesSetBool$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key, value],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> globalAttributesSetStringList({
    required String key,
    required List<String> value,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.globalAttributesSetStringList$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key, value],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> globalAttributesSetIntList({
    required String key,
    required List<int> value,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.globalAttributesSetIntList$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key, value],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> globalAttributesSetDoubleList({
    required String key,
    required List<double> value,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.globalAttributesSetDoubleList$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key, value],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> globalAttributesSetBoolList({
    required String key,
    required List<bool> value,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.globalAttributesSetBoolList$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key, value],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> globalAttributesSetAll({
    required GeneratedMutableAttributes value,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.globalAttributesSetAll$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[value],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> customTrackingTrackCustomEvent({
    required String name,
    required GeneratedMutableAttributes attributes,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.customTrackingTrackCustomEvent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[name, attributes],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<int> customTrackingStartWorkflow({
    required String workflowName,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.customTrackingStartWorkflow$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[workflowName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }

  Future<void> customTrackingEndWorkflow({
    required int handle,
    GeneratedMutableAttributes? attributes,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.customTrackingEndWorkflow$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, attributes],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> customTrackingTrackError({required GeneratedError error}) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.customTrackingTrackError$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[error],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> navigationTrack({
    required String screenName,
    GeneratedMutableAttributes? attributes,
  }) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.splunk_otel_flutter_platform_interface.SplunkOtelFlutterHostApi.navigationTrack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[screenName, attributes],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
