// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class SplunkOtelFlutterSessionReplayMessagesPigeonCodecReader: FlutterStandardReader {
}

private class SplunkOtelFlutterSessionReplayMessagesPigeonCodecWriter: FlutterStandardWriter {
}

private class SplunkOtelFlutterSessionReplayMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SplunkOtelFlutterSessionReplayMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SplunkOtelFlutterSessionReplayMessagesPigeonCodecWriter(data: data)
  }
}

class SplunkOtelFlutterSessionReplayMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SplunkOtelFlutterSessionReplayMessagesPigeonCodec(readerWriter: SplunkOtelFlutterSessionReplayMessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SplunkOtelFlutterSessionReplayHostApi {
  /// Starts session replay recording.
  ///
  /// Delegates to the native SDK's SessionReplay.start() via the
  /// SplunkRum.instance.sessionReplay extension.
  func startSessionReplay(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SplunkOtelFlutterSessionReplayHostApiSetup {
  static var codec: FlutterStandardMessageCodec { SplunkOtelFlutterSessionReplayMessagesPigeonCodec.shared }
  /// Sets up an instance of `SplunkOtelFlutterSessionReplayHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SplunkOtelFlutterSessionReplayHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Starts session replay recording.
    ///
    /// Delegates to the native SDK's SessionReplay.start() via the
    /// SplunkRum.instance.sessionReplay extension.
    let startSessionReplayChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.splunk_otel_flutter_session_replay_platform_interface.SplunkOtelFlutterSessionReplayHostApi.startSessionReplay\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startSessionReplayChannel.setMessageHandler { _, reply in
        api.startSessionReplay { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startSessionReplayChannel.setMessageHandler(nil)
    }
  }
}
