// Copyright 2026 Splunk Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsSplunkOtelFlutterSessionReplayMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashSplunkOtelFlutterSessionReplayMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsSplunkOtelFlutterSessionReplayMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsSplunkOtelFlutterSessionReplayMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsSplunkOtelFlutterSessionReplayMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsSplunkOtelFlutterSessionReplayMessages(lhsKey, rhsKey) {
          if deepEqualsSplunkOtelFlutterSessionReplayMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsSplunkOtelFlutterSessionReplayMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashSplunkOtelFlutterSessionReplayMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashSplunkOtelFlutterSessionReplayMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashSplunkOtelFlutterSessionReplayMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashSplunkOtelFlutterSessionReplayMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashSplunkOtelFlutterSessionReplayMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashSplunkOtelFlutterSessionReplayMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum GeneratedSessionReplayStatus: Int {
  case isRecording = 0
  case notStarted = 1
  case stopped = 2
  case belowMinSdkVersion = 3
  case storageLimitReached = 4
  case internalError = 5
  case disabledBySampling = 6
}

enum GeneratedRecordingMaskType: Int {
  case erasing = 0
  case covering = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct GeneratedRecordingMaskList: Hashable {
  var recordingMaskList: [GeneratedRecordingMaskElement]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GeneratedRecordingMaskList? {
    let recordingMaskList: [GeneratedRecordingMaskElement]? = nilOrValue(pigeonVar_list[0])

    return GeneratedRecordingMaskList(
      recordingMaskList: recordingMaskList
    )
  }
  func toList() -> [Any?] {
    return [
      recordingMaskList
    ]
  }
  static func == (lhs: GeneratedRecordingMaskList, rhs: GeneratedRecordingMaskList) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsSplunkOtelFlutterSessionReplayMessages(lhs.recordingMaskList, rhs.recordingMaskList)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GeneratedRecordingMaskList")
    deepHashSplunkOtelFlutterSessionReplayMessages(value: recordingMaskList, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GeneratedRecordingMaskElement: Hashable {
  var rect: GeneratedRect
  var type: GeneratedRecordingMaskType


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GeneratedRecordingMaskElement? {
    let rect = pigeonVar_list[0] as! GeneratedRect
    let type = pigeonVar_list[1] as! GeneratedRecordingMaskType

    return GeneratedRecordingMaskElement(
      rect: rect,
      type: type
    )
  }
  func toList() -> [Any?] {
    return [
      rect,
      type,
    ]
  }
  static func == (lhs: GeneratedRecordingMaskElement, rhs: GeneratedRecordingMaskElement) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsSplunkOtelFlutterSessionReplayMessages(lhs.rect, rhs.rect) && deepEqualsSplunkOtelFlutterSessionReplayMessages(lhs.type, rhs.type)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GeneratedRecordingMaskElement")
    deepHashSplunkOtelFlutterSessionReplayMessages(value: rect, hasher: &hasher)
    deepHashSplunkOtelFlutterSessionReplayMessages(value: type, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GeneratedRect: Hashable {
  var left: Double
  var top: Double
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GeneratedRect? {
    let left = pigeonVar_list[0] as! Double
    let top = pigeonVar_list[1] as! Double
    let width = pigeonVar_list[2] as! Double
    let height = pigeonVar_list[3] as! Double

    return GeneratedRect(
      left: left,
      top: top,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      left,
      top,
      width,
      height,
    ]
  }
  static func == (lhs: GeneratedRect, rhs: GeneratedRect) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsSplunkOtelFlutterSessionReplayMessages(lhs.left, rhs.left) && deepEqualsSplunkOtelFlutterSessionReplayMessages(lhs.top, rhs.top) && deepEqualsSplunkOtelFlutterSessionReplayMessages(lhs.width, rhs.width) && deepEqualsSplunkOtelFlutterSessionReplayMessages(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GeneratedRect")
    deepHashSplunkOtelFlutterSessionReplayMessages(value: left, hasher: &hasher)
    deepHashSplunkOtelFlutterSessionReplayMessages(value: top, hasher: &hasher)
    deepHashSplunkOtelFlutterSessionReplayMessages(value: width, hasher: &hasher)
    deepHashSplunkOtelFlutterSessionReplayMessages(value: height, hasher: &hasher)
  }
}

private class SplunkOtelFlutterSessionReplayMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return GeneratedSessionReplayStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return GeneratedRecordingMaskType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return GeneratedRecordingMaskList.fromList(self.readValue() as! [Any?])
    case 132:
      return GeneratedRecordingMaskElement.fromList(self.readValue() as! [Any?])
    case 133:
      return GeneratedRect.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SplunkOtelFlutterSessionReplayMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? GeneratedSessionReplayStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? GeneratedRecordingMaskType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? GeneratedRecordingMaskList {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? GeneratedRecordingMaskElement {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? GeneratedRect {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SplunkOtelFlutterSessionReplayMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SplunkOtelFlutterSessionReplayMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SplunkOtelFlutterSessionReplayMessagesPigeonCodecWriter(data: data)
  }
}

class SplunkOtelFlutterSessionReplayMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SplunkOtelFlutterSessionReplayMessagesPigeonCodec(readerWriter: SplunkOtelFlutterSessionReplayMessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SplunkOtelFlutterSessionReplayHostApi {
  func sessionReplayStart(completion: @escaping (Result<Void, Error>) -> Void)
  func sessionReplayStop(completion: @escaping (Result<Void, Error>) -> Void)
  func sessionReplayStateGetStatus(completion: @escaping (Result<GeneratedSessionReplayStatus, Error>) -> Void)
  func sessionReplayGetRecordingMask(completion: @escaping (Result<GeneratedRecordingMaskList?, Error>) -> Void)
  func sessionReplaySetRecordingMask(recordingMask: GeneratedRecordingMaskList?, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SplunkOtelFlutterSessionReplayHostApiSetup {
  static var codec: FlutterStandardMessageCodec { SplunkOtelFlutterSessionReplayMessagesPigeonCodec.shared }
  /// Sets up an instance of `SplunkOtelFlutterSessionReplayHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SplunkOtelFlutterSessionReplayHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let sessionReplayStartChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.splunk_otel_flutter_session_replay_platform_interface.SplunkOtelFlutterSessionReplayHostApi.sessionReplayStart\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sessionReplayStartChannel.setMessageHandler { _, reply in
        api.sessionReplayStart { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sessionReplayStartChannel.setMessageHandler(nil)
    }
    let sessionReplayStopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.splunk_otel_flutter_session_replay_platform_interface.SplunkOtelFlutterSessionReplayHostApi.sessionReplayStop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sessionReplayStopChannel.setMessageHandler { _, reply in
        api.sessionReplayStop { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sessionReplayStopChannel.setMessageHandler(nil)
    }
    let sessionReplayStateGetStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.splunk_otel_flutter_session_replay_platform_interface.SplunkOtelFlutterSessionReplayHostApi.sessionReplayStateGetStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sessionReplayStateGetStatusChannel.setMessageHandler { _, reply in
        api.sessionReplayStateGetStatus { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sessionReplayStateGetStatusChannel.setMessageHandler(nil)
    }
    let sessionReplayGetRecordingMaskChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.splunk_otel_flutter_session_replay_platform_interface.SplunkOtelFlutterSessionReplayHostApi.sessionReplayGetRecordingMask\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sessionReplayGetRecordingMaskChannel.setMessageHandler { _, reply in
        api.sessionReplayGetRecordingMask { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sessionReplayGetRecordingMaskChannel.setMessageHandler(nil)
    }
    let sessionReplaySetRecordingMaskChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.splunk_otel_flutter_session_replay_platform_interface.SplunkOtelFlutterSessionReplayHostApi.sessionReplaySetRecordingMask\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sessionReplaySetRecordingMaskChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let recordingMaskArg: GeneratedRecordingMaskList? = nilOrValue(args[0])
        api.sessionReplaySetRecordingMask(recordingMask: recordingMaskArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sessionReplaySetRecordingMaskChannel.setMessageHandler(nil)
    }
  }
}
