// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, unnecessary_import, no_leading_underscores_for_local_identifiers
// ignore_for_file: avoid_relative_lib_imports
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;
import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:splunk_otel_flutter_session_replay_platform_interface/src/pigeon/messages.pigeon.dart';


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is GeneratedSessionReplayStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is GeneratedRenderingMode) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is GeneratedRecordingMaskType) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is GeneratedRecordingMaskList) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is GeneratedRecordingMaskElement) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is GeneratedRect) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : GeneratedSessionReplayStatus.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : GeneratedRenderingMode.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : GeneratedRecordingMaskType.values[value];
      case 132: 
        return GeneratedRecordingMaskList.decode(readValue(buffer)!);
      case 133: 
        return GeneratedRecordingMaskElement.decode(readValue(buffer)!);
      case 134: 
        return GeneratedRect.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}
