name: splunk_otel_flutter_platform_interface
description: "Platform interface for Splunk OpenTelemetry Flutter instrumentation. Provides APIs for real user monitoring, tracing, and analytics."
version: 1.0.1
repository: https://github.com/signalfx/splunk-otel-flutter/tree/main/packages/splunk_otel_flutter/splunk_otel_flutter_platform_interface
homepage: https://github.com/signalfx/splunk-otel-flutter

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.32.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.0.1